### ISSUE TITLE
ImportError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by oddcoder** [NoviceLive/bintut#1]
I am running arch linux I got the bintut from pip2

```
➜  ~ bintut plain
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bintut/entry.py", line 24, in <module>
    from pkg_resources import resource_filename
ImportError: No module named 'pkg_resources'
```

hope it will be fixed soon :)

**Comment by NoviceLive** [comment]
Hi, it seems that you don't have `python-setuptools` (**NOT** `python2-setuptools`) installed.

On Linux, `entry.py` is meant to run inside GDB, which, on Arch, ships with Python 3. 
Therefore, `python-setuptools` is required and it will provide `pkg_resources`.

**Other required libraries used by code running inside GDB should also be installed by `pip3`**, which means just installing `python-setuptools` might not solve the problem. For convenience, you are advised to use `pip3` on Arch to get BinTut.

Thanks for reporting. I will mention it in the description. In later development, I will separate code that doesn't rely on GDB from that does.
