### ISSUE TITLE
ImportError: + UserWarning:

### ISSUE THREAD

**Issue by rezk2ll** [NoviceLive/bintut#2]
hello , after successfully installed the requirements ,i tried giving bintut a try , suddenly i got a warning about security !
after ignoring that i got an error saying the module pat is not found , ( i already installed it )

```
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/rezk2ll/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/home/rezk2ll/.python-eggs/BinTut-0.3.1_-py2.7.egg-tmp/bintut/entry.py", line 28, in <module>
    from courses.main import start_tutor
  File "/home/rezk2ll/.python-eggs/BinTut-0.3.1_-py2.7.egg-tmp/bintut/courses/main.py", line 28, in <module>
    from pat import Pat
ImportError: No module named 'pat'
```

any solution/s ?

**Comment by NoviceLive** [comment]
Hi, it seems that you installed bintut (and its dependencies) in the user directory and code running inside GDB couldn't find them. Current code base lacks a reasonable separation between code which must run inside GDB and those needn't.

At present, you are advised to install them globally using the pip whose version corresponds to the Python version shipped with GDB.

As for the warning, it's not related to bintut itself. You can check the access mode of  /home/rezk2ll/.python-eggs using stat and correct it using chmod, e.g, chmod 0600 /home/rezk2ll/.python-eggs.

**Comment by rezk2ll** [comment]
thanks @NoviceLive  , your solution worked perfectly !
i have gdb 7.7.1 wich is shipped with python3 , so i installed pip3 and reinstalled dependencies again with pip3.
thanks again .
